New: NuClick architecture
mostafajahanifar/mytiatoolbox pull request #1
Opened 2022-01-29 23:17 UTC by Jiaqi-Lv

Create NuClick Architecture in TIAToolBox.

- [ ] Define NuClick Architecture
- [ ] Add infer_batch
- [ ] Add postproc

2022-01-31 15:17 UTC, mostafajahanifar requested changes
Hi Jiaqi,
thanks copying over the NuClick architecture into thee TIAToolbox framework. I have made some comments, can you please go over them and then I will check if the imported architecture still works with our trained network. Thanks.

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +        if actv == 'selu':
Let get rid of everything related to `SeLU` sa we are not using it at all

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +        if actv != 'selu' and doBatchNorm:
`if doBatchNorm:`

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +"""(convolution => [BN] => ReLU/sigmoid)"""
Please follow this guidelines for writing docstrings:
https://github.com/TissueImageAnalytics/tiatoolbox/wiki/Docstrings

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +"""Multiscale Conv Block"""
follow docstring rules

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +        if isDense:
let's get rid of `isDense` and everything is related to it. Because we don't use it and it will confuse the review and testing process.

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +"""Residual_Conv"""
Docstrings

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +        if actv == 'selu':
delete selu part

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +class NuClick_NN(ModelABC):
Let's call it `NuClick` (drop the _NN part)

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +        imgs_points = batch_data
unnecessary `imgs_points` prameter definition. Do:
```
batch_data= batch_data.to(device).type(torch.float32)
with torch.inference_mode():
            output = model(batch_data)
...
```

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +    def infer_batch(model, batch_data, on_gpu):
we need docstring here as well.

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +    def postproc(preds, thresh=0.33, minSize=10, minHole=30, doReconstruction=False, nucPoints=None):
docstrings


I believe we should include `instance_dict` creation in this function as well. However, it should be in a way that can be update over different batches! so we should discuss how that can be implemented when we are working on the engine.

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +        masks = remove_small_objects(masks, min_size=minSize)
I will see if I can replace `remove_small_objects` and `remove_small_holes` with faster functions.

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +    #Returns masks
delete unnecessary comments

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +"""(convolution => [BN] => ReLU/sigmoid)"""
For fixed functions like `forward`, `postproc`, `infer_batch` which use the same structure or arguments as the ones in `models.architecture.unet`, you can copy/past the exact docstring from there. Also, use the same formatting as a template to complete new functions docstrings.

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +            if actv == 'sigmoid':
elif?

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +    def __init__(self, n_channels, n_classes):
make sure that naming of the arguments follow the same convention of other architectures in the TIAToolbox. For example, `n_channels` should be `num_input_channels`. Consider updating all arguments in a similar way. This is however only required for the main classes or functions. For the internal function/classes (like multi-scale conv block) you can use the old naming for the arguments,

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +    def __init__(self, n_channels, n_classes):
I'm saying this just for the sake of user experience in the future. User should be able to create Net architecture by calling different models API using the same argument convention.

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +    def forward(self, input):
docstring

2022-01-31 15:17 UTC, mostafajahanifar commented on tiatoolbox/models/architecture/nuclick.py
> +class NuClick_NN(ModelABC):
docstring. It should be detailed explaining the network and it's arguments also consider having an example.

2022-01-31 22:14 UTC, Jiaqi-Lv commented on tiatoolbox/models/architecture/nuclick.py
> +        masks = remove_small_objects(masks, min_size=minSize)
Sure

2022-02-03 16:38 UTC, Jiaqi-Lv commented on tiatoolbox/models/architecture/nuclick.py
> +    def postproc(preds, thresh=0.33, minSize=10, minHole=30, doReconstruction=False, nucPoints=None):
Yes

2022-02-03 20:46 UTC, mostafajahanifar reviewed
Thanks Jiaqi for making the changes.
I approve and merge this PR here so you can continue with the engine implementation, however, I will be improving the docstrings when I'm porting this to the original TIAToolbox.

Good luck

2022-02-03 20:46 UTC, merged